Committees/Reviewer:
  AAAI:
    url: https://aaai.org/Conferences/AAAI-21/
    years: 2021-2023

  ACL:
    url: https://2021.aclweb.org/
    years: 2021, 2023, 2024

  ACM-CS:
    years: ~2017, ~2023-2024

  ACM-TOPS:
    years: ~2020

  AISec:
    url: http://aisec2018.icsi.berkeley.edu/aisec2018/
    years: 2017

  ASIACCS:
    url: http://asiaccs2014.nict.go.jp
    years: 2014

  CCS:
    url: https://www.sigsac.org/ccs/CCS2020/
    years: 2016-2017, 2020, 2024

  CSF:
    url: https://www.ieee-security.org/CSFWweb
    years: 2013-2018, 2020, 2024,

  DAT:
    url: http://datworkshop.org
    years: 2016

  EMNLP:
    url: https://sigdat.org/
    years: 2023

  Entropy:
    years: ~2019

  FAccT:
    url: https://fatconference.org
    years: 2018, 2019, 2021

  FATML:
    url: https://www.fatml.org/schedule/2016
    years: 2016, 2017

  FCS:
    url: https://people.mpi-sws.org/~dg/events/fcs2016
    years: 2016

  ICALP:
    url: http://www.easyconferences.eu/icalp2016
    years: 2016

  ICLR:
    url: https://iclr.cc/
    years: 2024

  IJA:
    years: ~2017

  JCSS:
    years: ~2015

  LMCS:
    years: ~2017

  MILCOM:
    url: http://events.afcea.org/milcom16/public/enter.aspx
    years: 2016

  NDSS:
    url: http://www.ndss-symposium.org/ndss2017
    years: 2016-2017

  NeurIPS:
    url: https://neurips.cc/
    years: 2023

  PETS:
    url: https://www.petsymposium.org/2021/
    years: 2021

  PLAS:
    url: https://plas2018.dcc.ufmg.br
    years: 2018, 2019 (co-chair)

  POPL:
    url: https://popl.mpi-sws.org/2015
    years: 2013, 2015

  POST:
    url: https://www.etaps.org/index.php/2018/post
    years: 2018

  RAI:
    url: https://sites.google.com/view/rai-workshop/
    years: 2021 (area chair)

  S&P/Oakland:
    url: https://www.ieee-security.org/TC/SP2019/
    years: 2015-2020

  TCS:
    years: ~2017

  WPES:
    url: https://wpes.tech
    years: 2018, 2020


Other service:
  NSF:
    years: ~2018
